In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('~/OneDrive/DS PROJECTS/iris.csv')
df.head(10)

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa
5           5.4          3.9           1.7          0.4  setosa
6           4.6          3.4           1.4          0.3  setosa
7           5.0          3.4           1.5          0.2  setosa
8           4.4          2.9           1.4          0.2  setosa
9           4.9          3.1           1.5          0.1  setosa

In [3]:
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [5]:
df.describe()

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

#### Establishing Independent And Dependent Variables
* Independent : X = sepal_length, sepal_width, petal_length, petal_width
* Dependent : Y = species

In [7]:
# Select the first four columns of the dataset that describe the features of the flower
X = df.iloc[:,:4].values
# Select the last column of the dataset 
Y = df['species'].values
# displaying first 10 entries of X and Y
print(f"X \n {X[:10]}")
print("-"*25)
print(f"Y \n {Y[:10]}")

X 
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]
-------------------------
Y 
 ['setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa'
 'setosa' 'setosa']


#### Splitting Dataset

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2)
# display
print(f"X_train \n{X_train}")
print("-"*25)
print(f"X_test \n{X_test}")
print("-"*25)
print(f"Y_train \n{Y_train}")
print("-"*25)
print(f"Y_test \n{Y_test}")

X_train 
[[5.5 2.3 4.  1.3]
 [5.1 3.4 1.5 0.2]
 [6.1 2.9 4.7 1.4]
 [5.6 3.  4.5 1.5]
 [6.4 3.2 5.3 2.3]
 [4.7 3.2 1.6 0.2]
 [5.6 2.5 3.9 1.1]
 [7.2 3.  5.8 1.6]
 [5.5 4.2 1.4 0.2]
 [6.4 2.8 5.6 2.1]
 [6.1 2.8 4.7 1.2]
 [4.5 2.3 1.3 0.3]
 [6.3 2.5 4.9 1.5]
 [7.4 2.8 6.1 1.9]
 [7.7 2.6 6.9 2.3]
 [5.8 2.7 3.9 1.2]
 [6.  2.2 5.  1.5]
 [6.4 2.8 5.6 2.2]
 [6.7 3.1 4.7 1.5]
 [6.4 3.2 4.5 1.5]
 [5.  3.4 1.6 0.4]
 [5.1 3.5 1.4 0.3]
 [5.8 2.7 5.1 1.9]
 [7.2 3.6 6.1 2.5]
 [5.1 3.7 1.5 0.4]
 [6.4 3.1 5.5 1.8]
 [6.7 3.1 4.4 1.4]
 [4.3 3.  1.1 0.1]
 [5.7 3.  4.2 1.2]
 [6.3 2.9 5.6 1.8]
 [5.4 3.9 1.3 0.4]
 [5.9 3.  4.2 1.5]
 [7.9 3.8 6.4 2. ]
 [6.8 3.  5.5 2.1]
 [5.7 2.6 3.5 1. ]
 [6.5 3.  5.5 1.8]
 [4.9 3.  1.4 0.2]
 [5.5 2.4 3.7 1. ]
 [5.5 3.5 1.3 0.2]
 [5.7 2.8 4.5 1.3]
 [5.4 3.4 1.7 0.2]
 [5.2 4.1 1.5 0.1]
 [4.6 3.6 1.  0.2]
 [6.7 3.3 5.7 2.5]
 [5.  3.  1.6 0.2]
 [5.7 2.9 4.2 1.3]
 [5.  2.  3.5 1. ]
 [5.1 3.8 1.5 0.3]
 [6.5 3.2 5.1 2. ]
 [6.9 3.2 5.7 2.3]
 [6.8 2.8 4.8 1.4]
 [5.1 2.5 3.  1.1]
 [5

#### Feature Scaling

In [9]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

#### Building and Training the Naive Bayes Model on Training Set

In [10]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, Y_train)

GaussianNB()

#### Predicting Test Results

In [11]:
Y_pred = classifier.predict(X_test)
print(f"Y_pred \n {Y_pred}")

Y_pred 
 ['setosa' 'versicolor' 'setosa' 'virginica' 'virginica' 'versicolor'
 'virginica' 'virginica' 'setosa' 'virginica' 'setosa' 'virginica'
 'versicolor' 'setosa' 'setosa' 'virginica' 'virginica' 'versicolor'
 'virginica' 'setosa' 'setosa' 'virginica' 'setosa' 'versicolor'
 'versicolor' 'versicolor' 'setosa' 'virginica' 'virginica' 'versicolor']


#### Confusion Matrix and Accuracy

In [12]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
cm = confusion_matrix(Y_test, Y_pred)
print(f"Accuracy : {accuracy_score(Y_test, Y_pred)}")
print(f"Confusion Matrix:\n {cm}")

Accuracy : 0.9333333333333333
Confusion Matrix:
 [[10  0  0]
 [ 0  7  1]
 [ 0  1 11]]


#### Comparing Observable Prediction Results

In [13]:
df1 = pd.DataFrame({'Real Values':Y_test, 'Predicted Values':Y_pred})
df1

Real Values Predicted Values
0       setosa           setosa
1   versicolor       versicolor
2       setosa           setosa
3    virginica        virginica
4   versicolor        virginica
5   versicolor       versicolor
6    virginica        virginica
7    virginica        virginica
8       setosa           setosa
9    virginica        virginica
10      setosa           setosa
11   virginica        virginica
12  versicolor       versicolor
13      setosa           setosa
14      setosa           setosa
15   virginica        virginica
16   virginica        virginica
17   virginica       versicolor
18   virginica        virginica
19      setosa           setosa
20      setosa           setosa
21   virginica        virginica
22      setosa           setosa
23  versicolor       versicolor
24  versicolor       versicolor
25  versicolor       versicolor
26      setosa           setosa
27   virginica        virginica
28   virginica        virginica
29  versicolor       versicolor